apiVersion: v1
kind: Pod
metadata:
  name: watch-evaluator-lw-iris-pod
  labels:
    k8s-app: test-http2
spec:
  containers:
  - name: mypod
    image: "ghcr.io/lilyminium/openff-images:tmp-evaluator-dask-v5"
    env:
    - name: OE_LICENSE
      value: /secrets/oe_license.txt
    command:
      - "/bin/bash"
      - "-c"
      - "ls /evaluator-storage/stored_data/* | grep output | wc -l && sleep 600"

    volumeMounts:
    - name: evaluator-storage-lw-iris
      mountPath: /evaluator-storage
    - name: openeye-license
      mountPath: /secrets/oe_license.txt
      subPath: oe_license.txt
  volumes:
  - name: evaluator-storage-lw-iris
    persistentVolumeClaim:
      claimName: evaluator-storage-lw-iris

  - name: openeye-license
    secret:
      secretName: oe-license-feb-2025

